# Generated by LangForge — Earley parser
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any


@dataclass
class Position:
    line: int
    col: int
    offset: int


@dataclass
class TerminalNode:
    terminal_name: str
    token_type: str
    token_value: str
    position: Position | None = None


@dataclass
class NonTerminalNode:
    name: str
    children: list[Any] = field(default_factory=list)


_RULES = [
    ('sql_stmt', [('n', 'select_stmt')]),
    ('sql_stmt', [('n', 'insert_stmt')]),
    ('sql_stmt', [('n', 'update_stmt')]),
    ('sql_stmt', [('n', 'delete_stmt')]),
    ('select_stmt', [('t', '_LIT_0', '*', 'select'), ('n', 'sel_cols'), ('t', '_LIT_1', '*', 'from'), ('n', 'table_ref'), ('n', 'joins'), ('n', 'where_opt'), ('n', 'group_opt'), ('n', 'having_opt'), ('n', 'order_opt'), ('n', 'limit_opt'), ('n', 'offset_opt')]),
    ('sel_cols', [('t', 'STAR', 'STAR', None)]),
    ('sel_cols', [('n', 'col_items')]),
    ('col_items', [('n', 'col_item')]),
    ('col_items', [('n', 'col_items'), ('t', '_LIT_2', '*', ','), ('n', 'col_item')]),
    ('col_item', [('n', 'expr')]),
    ('col_item', [('n', 'expr'), ('t', '_LIT_3', '*', 'as'), ('t', 'IDENT', 'IDENT', None)]),
    ('table_ref', [('t', 'IDENT', 'IDENT', None)]),
    ('table_ref', [('t', 'IDENT', 'IDENT', None), ('t', 'IDENT', 'IDENT', None)]),
    ('table_ref', [('t', 'IDENT', 'IDENT', None), ('t', '_LIT_4', '*', 'as'), ('t', 'IDENT', 'IDENT', None)]),
    ('joins', []),
    ('joins', [('n', 'joins'), ('n', 'join_clause')]),
    ('join_clause', [('n', 'jointype'), ('t', '_LIT_5', '*', 'join'), ('n', 'table_ref'), ('t', '_LIT_6', '*', 'on'), ('n', 'expr')]),
    ('jointype', []),
    ('jointype', [('t', '_LIT_7', '*', 'inner')]),
    ('jointype', [('t', '_LIT_8', '*', 'left')]),
    ('jointype', [('t', '_LIT_9', '*', 'right')]),
    ('jointype', [('t', '_LIT_10', '*', 'full')]),
    ('jointype', [('t', '_LIT_11', '*', 'cross')]),
    ('where_opt', []),
    ('where_opt', [('t', '_LIT_12', '*', 'where'), ('n', 'expr')]),
    ('group_opt', []),
    ('group_opt', [('t', '_LIT_13', '*', 'group'), ('t', '_LIT_14', '*', 'by'), ('n', 'group_cols')]),
    ('group_cols', [('n', 'expr')]),
    ('group_cols', [('n', 'group_cols'), ('t', '_LIT_15', '*', ','), ('n', 'expr')]),
    ('having_opt', []),
    ('having_opt', [('t', '_LIT_16', '*', 'having'), ('n', 'expr')]),
    ('order_opt', []),
    ('order_opt', [('t', '_LIT_17', '*', 'order'), ('t', '_LIT_18', '*', 'by'), ('n', 'order_items')]),
    ('order_items', [('n', 'order_item')]),
    ('order_items', [('n', 'order_items'), ('t', '_LIT_19', '*', ','), ('n', 'order_item')]),
    ('order_item', [('n', 'expr')]),
    ('order_item', [('n', 'expr'), ('t', '_LIT_20', '*', 'asc')]),
    ('order_item', [('n', 'expr'), ('t', '_LIT_21', '*', 'desc')]),
    ('limit_opt', []),
    ('limit_opt', [('t', '_LIT_22', '*', 'limit'), ('t', 'INT', 'INT', None)]),
    ('offset_opt', []),
    ('offset_opt', [('t', '_LIT_23', '*', 'offset'), ('t', 'INT', 'INT', None)]),
    ('insert_stmt', [('t', '_LIT_24', '*', 'insert'), ('t', '_LIT_25', '*', 'into'), ('t', 'IDENT', 'IDENT', None), ('n', 'collist_opt'), ('t', '_LIT_26', '*', 'values'), ('n', 'rows')]),
    ('collist_opt', []),
    ('collist_opt', [('t', '_LIT_27', '*', '('), ('n', 'name_list'), ('t', '_LIT_28', '*', ')')]),
    ('name_list', [('t', 'IDENT', 'IDENT', None)]),
    ('name_list', [('n', 'name_list'), ('t', '_LIT_29', '*', ','), ('t', 'IDENT', 'IDENT', None)]),
    ('rows', [('n', 'row')]),
    ('rows', [('n', 'rows'), ('t', '_LIT_30', '*', ','), ('n', 'row')]),
    ('row', [('t', '_LIT_31', '*', '('), ('n', 'val_list'), ('t', '_LIT_32', '*', ')')]),
    ('val_list', [('n', 'expr')]),
    ('val_list', [('n', 'val_list'), ('t', '_LIT_33', '*', ','), ('n', 'expr')]),
    ('update_stmt', [('t', '_LIT_34', '*', 'update'), ('t', 'IDENT', 'IDENT', None), ('t', '_LIT_35', '*', 'set'), ('n', 'assigns'), ('n', 'where_or_all')]),
    ('assigns', [('n', 'assign_one')]),
    ('assigns', [('n', 'assigns'), ('t', '_LIT_36', '*', ','), ('n', 'assign_one')]),
    ('assign_one', [('t', 'IDENT', 'IDENT', None), ('t', '_LIT_37', '*', '='), ('n', 'expr')]),
    ('where_or_all', [('t', '_LIT_38', '*', 'where'), ('n', 'expr')]),
    ('where_or_all', [('t', '_LIT_39', '*', 'all')]),
    ('delete_stmt', [('t', '_LIT_40', '*', 'delete'), ('t', '_LIT_41', '*', 'from'), ('t', 'IDENT', 'IDENT', None), ('n', 'where_or_all')]),
    ('expr', [('n', 'orx')]),
    ('orx', [('n', 'orx'), ('t', '_LIT_42', '*', 'or'), ('n', 'andx')]),
    ('orx', [('n', 'andx')]),
    ('andx', [('n', 'andx'), ('t', '_LIT_43', '*', 'and'), ('n', 'notx')]),
    ('andx', [('n', 'notx')]),
    ('notx', [('t', '_LIT_44', '*', 'not'), ('n', 'notx')]),
    ('notx', [('n', 'cmp')]),
    ('cmp', [('n', 'cmp'), ('n', 'cmpop'), ('n', 'addx')]),
    ('cmp', [('n', 'addx'), ('n', 'cmp_in')]),
    ('cmp', [('n', 'addx')]),
    ('cmpop', [('t', '_LIT_45', '*', '=')]),
    ('cmpop', [('t', '_LIT_46', '*', '<>')]),
    ('cmpop', [('t', '_LIT_47', '*', '!=')]),
    ('cmpop', [('t', '_LIT_48', '*', '<')]),
    ('cmpop', [('t', '_LIT_49', '*', '<=')]),
    ('cmpop', [('t', '_LIT_50', '*', '>')]),
    ('cmpop', [('t', '_LIT_51', '*', '>=')]),
    ('cmp_in', [('t', '_LIT_52', '*', 'in'), ('t', '_LIT_53', '*', '('), ('n', 'val_list'), ('t', '_LIT_54', '*', ')')]),
    ('addx', [('n', 'addx'), ('t', '_LIT_55', '*', '+'), ('n', 'mulx')]),
    ('addx', [('n', 'addx'), ('t', '_LIT_56', '*', '-'), ('n', 'mulx')]),
    ('addx', [('n', 'mulx')]),
    ('mulx', [('n', 'mulx'), ('t', '_LIT_57', '*', '*'), ('n', 'atom')]),
    ('mulx', [('n', 'mulx'), ('t', '_LIT_58', '*', '/'), ('n', 'atom')]),
    ('mulx', [('n', 'mulx'), ('t', '_LIT_59', '*', '%'), ('n', 'atom')]),
    ('mulx', [('n', 'atom')]),
    ('atom', [('t', 'INT', 'INT', None)]),
    ('atom', [('t', 'FLOAT', 'FLOAT', None)]),
    ('atom', [('t', 'STRING', 'STRING', None)]),
    ('atom', [('t', '_LIT_60', '*', 'null')]),
    ('atom', [('t', '_LIT_61', '*', 'true')]),
    ('atom', [('t', '_LIT_62', '*', 'false')]),
    ('atom', [('n', 'read')]),
    ('atom', [('n', 'colref')]),
    ('atom', [('n', 'func')]),
    ('atom', [('t', '_LIT_63', '*', '('), ('n', 'expr'), ('t', '_LIT_64', '*', ')')]),
    ('read', [('t', '_LIT_65', '*', '$('), ('t', 'POINTER', 'POINTER', None), ('t', '_LIT_66', '*', ')')]),
    ('colref', [('t', 'IDENT', 'IDENT', None)]),
    ('colref', [('t', 'IDENT', 'IDENT', None), ('t', '_LIT_67', '*', '.'), ('t', 'IDENT', 'IDENT', None)]),
    ('colref', [('t', 'IDENT', 'IDENT', None), ('t', '_LIT_68', '*', '.'), ('t', 'STAR', 'STAR', None)]),
    ('func', [('t', 'IDENT', 'IDENT', None), ('t', '_LIT_69', '*', '('), ('n', 'func_args'), ('t', '_LIT_70', '*', ')')]),
    ('func_args', []),
    ('func_args', [('t', '_LIT_71', '*', 'distinct'), ('n', 'arg_list')]),
    ('func_args', [('n', 'arg_list')]),
    ('func_args', [('t', 'STAR', 'STAR', None)]),
    ('arg_list', [('n', 'expr')]),
    ('arg_list', [('n', 'arg_list'), ('t', '_LIT_72', '*', ','), ('n', 'expr')]),
]

_NT_INDEX = {'sql_stmt': [0, 1, 2, 3], 'select_stmt': [4], 'sel_cols': [5, 6], 'col_items': [7, 8], 'col_item': [9, 10], 'table_ref': [11, 12, 13], 'joins': [14, 15], 'join_clause': [16], 'jointype': [17, 18, 19, 20, 21, 22], 'where_opt': [23, 24], 'group_opt': [25, 26], 'group_cols': [27, 28], 'having_opt': [29, 30], 'order_opt': [31, 32], 'order_items': [33, 34], 'order_item': [35, 36, 37], 'limit_opt': [38, 39], 'offset_opt': [40, 41], 'insert_stmt': [42], 'collist_opt': [43, 44], 'name_list': [45, 46], 'rows': [47, 48], 'row': [49], 'val_list': [50, 51], 'update_stmt': [52], 'assigns': [53, 54], 'assign_one': [55], 'where_or_all': [56, 57], 'delete_stmt': [58], 'expr': [59], 'orx': [60, 61], 'andx': [62, 63], 'notx': [64, 65], 'cmp': [66, 67, 68], 'cmpop': [69, 70, 71, 72, 73, 74, 75], 'cmp_in': [76], 'addx': [77, 78, 79], 'mulx': [80, 81, 82, 83], 'atom': [84, 85, 86, 87, 88, 89, 90, 91, 92, 93], 'read': [94], 'colref': [95, 96, 97], 'func': [98], 'func_args': [99, 100, 101, 102], 'arg_list': [103, 104]}
_START = 'sql_stmt'

def _matches(sym, token_type, token_value):
    _, name, tok_t, tok_v = sym
    if tok_t != '*' and token_type != tok_t:
        return False
    if tok_v is not None and token_value != tok_v:
        return False
    return True


def _parse_earley(tokens):
    n = len(tokens)
    chart = [[] for _ in range(n + 1)]
    in_chart = [set() for _ in range(n + 1)]

    def add(i, item):
        if item not in in_chart[i]:
            chart[i].append(item)
            in_chart[i].add(item)

    for ri in _NT_INDEX.get(_START, []):
        add(0, (ri, 0, 0))

    for i in range(n + 1):
        j = 0
        while j < len(chart[i]):
            rule_idx, dot, origin = chart[i][j]
            j += 1
            head, body = _RULES[rule_idx]
            if dot == len(body):
                for p_ri, p_dot, p_orig in chart[origin]:
                    _, p_body = _RULES[p_ri]
                    if p_dot < len(p_body) and p_body[p_dot][0] == 'n' and p_body[p_dot][1] == head:
                        add(i, (p_ri, p_dot + 1, p_orig))
            elif body[dot][0] == 'n':
                for ri in _NT_INDEX.get(body[dot][1], []):
                    add(i, (ri, 0, i))
            else:
                if i < n and _matches(body[dot], tokens[i].type, tokens[i].value):
                    add(i + 1, (rule_idx, dot + 1, origin))

    completed = {}
    for e, items in enumerate(chart):
        for rule_idx, dot, origin in items:
            head, body = _RULES[rule_idx]
            if dot == len(body):
                key = (head, origin, e)
                if key in completed:
                    completed[key].append(rule_idx)
                else:
                    completed[key] = [rule_idx]

    _memo = {}

    def _recover(ri, s, e):
        _result = None
        stack = [('R', ri, s, e)]

        while stack:
            tag = stack[-1][0]

            if tag == 'R':
                _, ri_, s_, e_ = stack.pop()
                key = ('r', ri_, s_, e_)
                if key in _memo:
                    _result = _memo[key]
                else:
                    head_, body_ = _RULES[ri_]
                    stack.append(('R_DONE', key, head_))
                    stack.append(('B', body_, 0, s_, e_))

            elif tag == 'R_DONE':
                _, key, head_ = stack.pop()
                _result = NonTerminalNode(head_, _result) if _result is not None else None
                _memo[key] = _result

            elif tag == 'B':
                _, body_, pos_, s_, e_ = stack.pop()
                bkey = (id(body_), pos_, s_, e_)
                if bkey in _memo:
                    _result = _memo[bkey]
                elif pos_ >= len(body_):
                    _result = [] if s_ == e_ else None
                    _memo[bkey] = _result
                else:
                    sym_ = body_[pos_]
                    if sym_[0] == 't':
                        if s_ >= e_ or not _matches(sym_, tokens[s_].type, tokens[s_].value):
                            _result = None
                            _memo[bkey] = None
                        else:
                            _p = tokens[s_].position
                            _tpos = Position(_p.line, _p.col, _p.offset) if _p is not None else None
                            tnode = TerminalNode(sym_[1], tokens[s_].type, tokens[s_].value, _tpos)
                            stack.append(('B_TERM_DONE', bkey, tnode))
                            stack.append(('B', body_, pos_ + 1, s_ + 1, e_))
                    else:
                        stack.append(('B_NT_LOOP', bkey, body_, pos_, s_, e_, sym_[1], s_))

            elif tag == 'B_TERM_DONE':
                _, bkey, tnode = stack.pop()
                if _result is None:
                    _memo[bkey] = None
                else:
                    _result = [tnode] + _result
                    _memo[bkey] = _result

            elif tag == 'B_NT_LOOP':
                _, bkey, body_, pos_, s_, e_, name_, mid_ = stack.pop()
                if mid_ > e_:
                    _result = None
                    _memo[bkey] = None
                else:
                    stack.append(('B_NT_AFTER_FIND', bkey, body_, pos_, s_, e_, name_, mid_))
                    stack.append(('F', name_, s_, mid_))

            elif tag == 'B_NT_AFTER_FIND':
                _, bkey, body_, pos_, s_, e_, name_, mid_ = stack.pop()
                node_ = _result
                if node_ is None:
                    stack.append(('B_NT_LOOP', bkey, body_, pos_, s_, e_, name_, mid_ + 1))
                else:
                    stack.append(('B_NT_AFTER_TAIL', bkey, body_, pos_, s_, e_, name_, mid_, node_))
                    stack.append(('B', body_, pos_ + 1, mid_, e_))

            elif tag == 'B_NT_AFTER_TAIL':
                _, bkey, body_, pos_, s_, e_, name_, mid_, node_ = stack.pop()
                tail_ = _result
                if tail_ is None:
                    stack.append(('B_NT_LOOP', bkey, body_, pos_, s_, e_, name_, mid_ + 1))
                else:
                    _result = [node_] + tail_
                    _memo[bkey] = _result

            elif tag == 'F':
                _, name_, s_, e_ = stack.pop()
                fkey = ('f', name_, s_, e_)
                if fkey in _memo:
                    _result = _memo[fkey]
                else:
                    items_ = completed.get((name_, s_, e_), [])
                    if not items_:
                        _result = None
                        _memo[fkey] = None
                    else:
                        stack.append(('F_NEXT', fkey, s_, e_, items_, 0))
                        stack.append(('R', items_[0], s_, e_))

            elif tag == 'F_NEXT':
                _, fkey, s_, e_, items_, idx_ = stack.pop()
                node_ = _result
                if node_ is not None:
                    _result = node_
                    _memo[fkey] = node_
                elif idx_ + 1 < len(items_):
                    stack.append(('F_NEXT', fkey, s_, e_, items_, idx_ + 1))
                    stack.append(('R', items_[idx_ + 1], s_, e_))
                else:
                    _result = None
                    _memo[fkey] = None

        return _result

    for rule_idx, dot, origin in chart[n]:
        head, body = _RULES[rule_idx]
        if head == _START and dot == len(body) and origin == 0:
            node = _recover(rule_idx, 0, n)
            if node is not None:
                return node
    raise ValueError('Parse failed')


def parse(tokens):
    return _parse_earley(list(tokens))

