# Generated by LangForge — standalone lexer
from __future__ import annotations
import re
from dataclasses import dataclass, field
from typing import Iterator

_RE_root_r0 = re.compile('\\n(?P<ws>[ \\t]*)')
_RE_root_r1 = re.compile('[ \\t]+')
_RE_root_r2 = re.compile('#[^\\n]*')
_RE_root_r3 = re.compile('"(?:[^"\\\\]|\\\\.)*"')
_RE_root_r4 = re.compile('\\$\\(')
_RE_root_r5 = re.compile('(?:[@&!_]:)?/[a-zA-Z_][A-Za-z0-9_./~-]*')
_RE_root_r6 = re.compile('(?:[@&!_]:)?/')
_RE_root_r7 = re.compile('[0-9]+\\.[0-9]+')
_RE_root_r8 = re.compile('[0-9]+')
_RE_root_r9 = re.compile('<\\-!')
_RE_root_r10 = re.compile('<\\-')
_RE_root_r11 = re.compile('==')
_RE_root_r12 = re.compile('!=')
_RE_root_r13 = re.compile('<=')
_RE_root_r14 = re.compile('>=')
_RE_root_r15 = re.compile('\\*\\*')
_RE_root_r16 = re.compile('\\?\\?')
_RE_root_r17 = re.compile('(?:continue|foreach|finally|except|return|exists|assert|while|raise|break|false|elif|else|exit|exec|true|null|try|def|and|not|del|raw|in|do|if|or|op)(?!\\w)')
_RE_root_r18 = re.compile('[a-zA-Z_](?:[a-zA-Z_]|[0-9])*')
_RE_root_r19 = re.compile('\\(')
_RE_root_r20 = re.compile('\\)')
_RE_root_r21 = re.compile('\\[')
_RE_root_r22 = re.compile('\\]')
_RE_root_r23 = re.compile('\\{')
_RE_root_r24 = re.compile('\\}')
_RE_root_r25 = re.compile('<')
_RE_root_r26 = re.compile('>')
_RE_root_r27 = re.compile('\\+')
_RE_root_r28 = re.compile('\\-')
_RE_root_r29 = re.compile('\\*')
_RE_root_r30 = re.compile('/')
_RE_root_r31 = re.compile('%')
_RE_root_r32 = re.compile('=')
_RE_root_r33 = re.compile(',')
_RE_root_r34 = re.compile(':')
_RE_root_r35 = re.compile(';')
_RE_root_r36 = re.compile('\\.')
_RE_root_r37 = re.compile('!')

_DYN_TEMPLATES = {}
_STATE_FUNCS = {'root': '_lex_root'}
_EOF_CONFIGS = {'root': {'emit': ['NEWLINE'], 'error': None}}

_INTERP_RE = re.compile(r'\$\{meta\.([A-Za-z_][A-Za-z0-9_]*)(?:\|([a-z]+))?\}')


def _build_dyn_regex(template, meta):
    def _r(m):
        k = m.group(1); mod = m.group(2)
        v = str(meta.get(k, ''))
        return v if mod == 'raw' else re.escape(v)
    return re.compile(_INTERP_RE.sub(_r, template))


def _build_dyn_delimiter(template, meta):
    return _build_dyn_regex(template, meta)


def _kw_match(regex, text, pos):
    m = regex.match(text, pos)
    if m is None:
        return None
    if pos > 0 and re.match(r'\w', text[pos - 1]):
        return None
    return m


def _until_match(delim_re, text, pos):
    m = delim_re.search(text, pos)
    end = m.start() if m else len(text)
    if end == pos:
        return None
    return re.compile(re.escape(text[pos:end])).match(text, pos)


def _tmpl_resolve(config, m):
    template = config['template']
    captures = config.get('captures', {})
    result = template
    for placeholder, group_name in captures.items():
        result = result.replace(f'${{{placeholder}}}', m.group(group_name))
    return result


def _pos(text, pos):
    lines_before = text[:pos].split('\n')
    return _Position(len(lines_before), len(lines_before[-1]) + 1, pos)


@dataclass
class _Position:
    line: int
    col: int
    offset: int


@dataclass
class _Token:
    type: str
    value: str
    position: _Position


@dataclass
class _Frame:
    state: str
    meta: dict
    _dyn: list = field(default_factory=list)
    _buf: str = ''
    _compiled_state: str = ''

def _compile_frame_dyn(state_name, meta):
    _r = []
    for kind, tmpl in _DYN_TEMPLATES.get(state_name, []):
        if kind == 'dyn_pattern':
            _r.append(_build_dyn_regex(tmpl, meta))
        else:
            _r.append(_build_dyn_delimiter(tmpl, meta))
    return _r

def _lex_root(text, pos, stack, frame):
    m = _RE_root_r0.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('INIT', m.group(), _pos(text, pos))]
        if not ((not bool(frame.meta.get('paren_depth'))) and (not frame.meta.get('indent_stack'))):
            _toks = []
        if _toks:
            frame.meta['indent_stack'] = (list(frame.meta.get('indent_stack')) if frame.meta.get('indent_stack') is not None else []) + [0]
        _toks = []
        _result.extend(_toks)
        _toks = [_Token('NEWLINE', m.group(), _pos(text, pos))]
        if not (not bool(frame.meta.get('paren_depth'))):
            _toks = []
        _result.extend(_toks)
        _toks = [_Token('DEDENT', m.group(), _pos(text, pos))]
        if not (not bool(frame.meta.get('paren_depth'))):
            _toks = []
        _rep_toks = []
        while (bool(frame.meta.get('indent_stack')) and frame.meta.get('indent_stack')[-1] > len(m.group('ws'))):
            _rep_toks.extend(list(_toks))
            frame.meta['indent_stack'] = (lambda _l: (_l.pop(), _l)[1])(list(frame.meta.get('indent_stack')))
        _toks = _rep_toks
        _result.extend(_toks)
        _toks = [_Token('INDENT', m.group(), _pos(text, pos))]
        if not ((not bool(frame.meta.get('paren_depth'))) and ((bool(frame.meta.get('indent_stack')) and frame.meta.get('indent_stack')[-1] < len(m.group('ws'))))):
            _toks = []
        if _toks:
            frame.meta['indent_stack'] = (list(frame.meta.get('indent_stack')) if frame.meta.get('indent_stack') is not None else []) + [len(m.group('ws'))]
        _result.extend(_toks)
        return _result, m.end()
    m = _RE_root_r1.match(text, pos)
    if m is not None:
        return [], m.end()
    m = _RE_root_r2.match(text, pos)
    if m is not None:
        return [], m.end()
    m = _RE_root_r3.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('STRING', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    m = _RE_root_r4.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('DOLLAR_LPAREN', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        frame.meta['paren_depth'] = (frame.meta.get('paren_depth') or 0) + 1
        return _result, m.end()
    m = _RE_root_r5.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('POINTER', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    m = _RE_root_r6.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('POINTER', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    m = _RE_root_r7.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('FLOAT', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    m = _RE_root_r8.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('INT', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    m = _RE_root_r9.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('COPY_STRICT', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    m = _RE_root_r10.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('COPY', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    m = _RE_root_r11.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('EQ', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    m = _RE_root_r12.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('NE', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    m = _RE_root_r13.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('LE', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    m = _RE_root_r14.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('GE', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    m = _RE_root_r15.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('POW', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    m = _RE_root_r16.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('COALESCE', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    m = _kw_match(_RE_root_r17, text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('KW', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    m = _RE_root_r18.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('IDENT', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    m = _RE_root_r19.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('LPAREN', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        frame.meta['paren_depth'] = (frame.meta.get('paren_depth') or 0) + 1
        return _result, m.end()
    m = _RE_root_r20.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('RPAREN', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        frame.meta['paren_depth'] = (frame.meta.get('paren_depth') or 0) - 1
        return _result, m.end()
    m = _RE_root_r21.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('LBRACKET', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        frame.meta['paren_depth'] = (frame.meta.get('paren_depth') or 0) + 1
        return _result, m.end()
    m = _RE_root_r22.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('RBRACKET', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        frame.meta['paren_depth'] = (frame.meta.get('paren_depth') or 0) - 1
        return _result, m.end()
    m = _RE_root_r23.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('LBRACE', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    m = _RE_root_r24.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('RBRACE', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    m = _RE_root_r25.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('LT', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    m = _RE_root_r26.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('GT', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    m = _RE_root_r27.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('PLUS', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    m = _RE_root_r28.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('MINUS', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    m = _RE_root_r29.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('STAR', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    m = _RE_root_r30.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('SLASH', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    m = _RE_root_r31.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('PERCENT', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    m = _RE_root_r32.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('ASSIGN', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    m = _RE_root_r33.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('COMMA', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    m = _RE_root_r34.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('COLON', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    m = _RE_root_r35.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('SEMI', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    m = _RE_root_r36.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('DOT', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    m = _RE_root_r37.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('BANG', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    return None

class Lexer:
    def tokenize(self, text: str) -> Iterator[_Token]:
        frame = _Frame('root', {})
        frame._dyn = _compile_frame_dyn('root', {})
        stack = [frame]
        pos = 0
        while pos < len(text):
            frame = stack[-1]
            # re-compile dyn rules if state changed via set_state
            if frame._compiled_state != frame.state:
                frame._dyn = _compile_frame_dyn(frame.state, frame.meta)
                frame._compiled_state = frame.state
            _fn_name = _STATE_FUNCS.get(frame.state)
            if _fn_name is None:
                raise ValueError(f"Unknown state {frame.state!r}")
            _fn = globals()[_fn_name]
            result = _fn(text, pos, stack, frame)
            if result is None and False:
                result = _lex___global__(text, pos, stack, frame)
            if result is None:
                _lines = text[:pos].split('\n')
                _loc = f'{len(_lines)}:{len(_lines[-1]) + 1}'
                raise ValueError(
                    f"No rule matched in state {frame.state!r} at {_loc}: "
                    f"{text[pos:pos+20]!r}"
                )
            tokens, new_pos = result
            # update top frame after possible push/set_state
            top = stack[-1]
            if top._compiled_state != top.state:
                top._dyn = _compile_frame_dyn(top.state, top.meta)
                top._compiled_state = top.state
            yield from tokens
            pos = new_pos

        frame = stack[-1]
        eof_cfg = _EOF_CONFIGS.get(frame.state)
        if eof_cfg:
            if eof_cfg.get('error'):
                raise SyntaxError(eof_cfg['error'])
            lines_before = text.split('\n')
            _p = _Position(len(lines_before), len(lines_before[-1]) + 1, len(text))
            for token_type in eof_cfg.get('emit', []):
                yield _Token(token_type, '', _p)

