# Generated by LangForge — Earley parser
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any


@dataclass
class Position:
    line: int
    col: int
    offset: int


@dataclass
class TerminalNode:
    terminal_name: str
    token_type: str
    token_value: str
    position: Position | None = None


@dataclass
class NonTerminalNode:
    name: str
    children: list[Any] = field(default_factory=list)


_RULES = [
    ('program', [('n', 'block')]),
    ('block', [('n', 'seps_opt')]),
    ('block', [('n', 'seps_opt'), ('n', 'stmts')]),
    ('stmts', [('n', 'stmt'), ('n', 'seps_opt')]),
    ('stmts', [('n', 'stmts'), ('n', 'stmt'), ('n', 'seps_opt')]),
    ('seps_opt', []),
    ('seps_opt', [('n', 'seps_opt'), ('n', 'sep')]),
    ('seps', [('n', 'sep')]),
    ('seps', [('n', 'seps'), ('n', 'sep')]),
    ('sep', [('t', 'NEWLINE', 'NEWLINE', None)]),
    ('sep', [('t', '_LIT_0', '*', ';')]),
    ('stmt', [('n', 'assign')]),
    ('stmt', [('n', 'copy')]),
    ('stmt', [('n', 'del')]),
    ('stmt', [('n', 'assertst')]),
    ('stmt', [('n', 'ifst')]),
    ('stmt', [('n', 'foreachst')]),
    ('stmt', [('n', 'whilest')]),
    ('stmt', [('n', 'dowhilest')]),
    ('stmt', [('n', 'tryst')]),
    ('stmt', [('n', 'defst')]),
    ('stmt', [('n', 'returnst')]),
    ('stmt', [('n', 'raisest')]),
    ('stmt', [('n', 'breakst')]),
    ('stmt', [('n', 'continuest')]),
    ('stmt', [('n', 'exitst')]),
    ('stmt', [('n', 'execst')]),
    ('stmt', [('n', 'opst')]),
    ('stmt', [('n', 'opfnst')]),
    ('stmt', [('n', 'callstmt')]),
    ('suite', [('t', '_LIT_1', '*', ':'), ('t', 'NEWLINE', 'NEWLINE', None), ('t', 'INDENT', 'INDENT', None), ('n', 'block'), ('t', 'DEDENT', 'DEDENT', None)]),
    ('suite', [('t', '_LIT_2', '*', ':'), ('n', 'stmt')]),
    ('suite', [('t', '_LIT_3', '*', '{'), ('n', 'block'), ('t', '_LIT_4', '*', '}')]),
    ('assign', [('t', 'POINTER', 'POINTER', None), ('t', '_LIT_5', '*', '='), ('n', 'expr')]),
    ('assign', [('t', 'POINTER', 'POINTER', None), ('t', '_LIT_6', '*', '['), ('t', '_LIT_7', '*', ']'), ('t', '_LIT_8', '*', '='), ('n', 'expr')]),
    ('copy', [('t', 'POINTER', 'POINTER', None), ('t', '_LIT_9', '*', '<-'), ('t', 'POINTER', 'POINTER', None)]),
    ('copy', [('t', 'POINTER', 'POINTER', None), ('t', '_LIT_10', '*', '<-'), ('t', 'POINTER', 'POINTER', None), ('t', '_LIT_11', '*', '??'), ('n', 'expr')]),
    ('copy', [('t', 'POINTER', 'POINTER', None), ('t', '_LIT_12', '*', '<-!'), ('t', 'POINTER', 'POINTER', None)]),
    ('del', [('t', '_LIT_13', '*', 'del'), ('n', 'ptr_list')]),
    ('del', [('t', '_LIT_14', '*', 'del'), ('t', '_LIT_15', '*', '!'), ('n', 'ptr_list')]),
    ('ptr_list', [('t', 'POINTER', 'POINTER', None)]),
    ('ptr_list', [('n', 'ptr_list'), ('t', '_LIT_16', '*', ','), ('t', 'POINTER', 'POINTER', None)]),
    ('assertst', [('t', '_LIT_17', '*', 'assert'), ('t', 'POINTER', 'POINTER', None)]),
    ('assertst', [('t', '_LIT_18', '*', 'assert'), ('t', 'POINTER', 'POINTER', None), ('t', '_LIT_19', '*', '=='), ('n', 'expr')]),
    ('ifst', [('t', '_LIT_20', '*', 'if'), ('n', 'expr'), ('n', 'suite'), ('n', 'elifs'), ('n', 'else_opt')]),
    ('elifs', []),
    ('elifs', [('n', 'elifs'), ('t', '_LIT_21', '*', 'elif'), ('n', 'expr'), ('n', 'suite')]),
    ('elifs', [('n', 'elifs'), ('n', 'seps'), ('t', '_LIT_22', '*', 'elif'), ('n', 'expr'), ('n', 'suite')]),
    ('else_opt', []),
    ('else_opt', [('t', '_LIT_23', '*', 'else'), ('n', 'suite')]),
    ('else_opt', [('n', 'seps'), ('t', '_LIT_24', '*', 'else'), ('n', 'suite')]),
    ('foreachst', [('t', '_LIT_25', '*', 'foreach'), ('t', 'IDENT', 'IDENT', None), ('t', '_LIT_26', '*', 'in'), ('n', 'expr'), ('n', 'suite')]),
    ('foreachst', [('t', '_LIT_27', '*', 'foreach'), ('t', 'IDENT', 'IDENT', None), ('t', '_LIT_28', '*', 'in'), ('n', 'expr'), ('t', '_LIT_29', '*', 'default'), ('n', 'expr'), ('n', 'suite')]),
    ('whilest', [('t', '_LIT_30', '*', 'while'), ('n', 'expr'), ('n', 'suite')]),
    ('dowhilest', [('t', '_LIT_31', '*', 'do'), ('n', 'suite'), ('t', '_LIT_32', '*', 'while'), ('n', 'expr')]),
    ('tryst', [('t', '_LIT_33', '*', 'try'), ('n', 'suite'), ('n', 'except_opt'), ('n', 'finally_opt')]),
    ('except_opt', []),
    ('except_opt', [('t', '_LIT_34', '*', 'except'), ('n', 'suite')]),
    ('finally_opt', []),
    ('finally_opt', [('t', '_LIT_35', '*', 'finally'), ('n', 'suite')]),
    ('defst', [('t', '_LIT_36', '*', 'def'), ('t', 'IDENT', 'IDENT', None), ('t', '_LIT_37', '*', '('), ('n', 'params'), ('t', '_LIT_38', '*', ')'), ('n', 'defopts'), ('n', 'suite'), ('n', 'failopt')]),
    ('params', []),
    ('params', [('n', 'param_list')]),
    ('param_list', [('t', 'IDENT', 'IDENT', None)]),
    ('param_list', [('n', 'param_list'), ('t', '_LIT_39', '*', ','), ('t', 'IDENT', 'IDENT', None)]),
    ('defopts', []),
    ('defopts', [('t', '_LIT_40', '*', 'context'), ('t', '_LIT_41', '*', '='), ('t', 'IDENT', 'IDENT', None)]),
    ('failopt', []),
    ('failopt', [('t', '_LIT_42', '*', 'on_failure'), ('n', 'suite')]),
    ('returnst', [('t', '_LIT_43', '*', 'return')]),
    ('returnst', [('t', '_LIT_44', '*', 'return'), ('n', 'expr')]),
    ('raisest', [('t', '_LIT_45', '*', 'raise'), ('n', 'expr')]),
    ('breakst', [('t', '_LIT_46', '*', 'break')]),
    ('continuest', [('t', '_LIT_47', '*', 'continue')]),
    ('exitst', [('t', '_LIT_48', '*', 'exit')]),
    ('execst', [('t', '_LIT_49', '*', 'exec'), ('t', 'POINTER', 'POINTER', None)]),
    ('execst', [('t', '_LIT_50', '*', 'exec'), ('t', 'POINTER', 'POINTER', None), ('t', '_LIT_51', '*', 'merge')]),
    ('execst', [('t', '_LIT_52', '*', 'exec'), ('n', 'suite')]),
    ('opst', [('t', '_LIT_53', '*', 'op'), ('t', 'STRING', 'STRING', None), ('t', '_LIT_54', '*', '('), ('n', 'args'), ('t', '_LIT_55', '*', ')'), ('n', 'suite')]),
    ('opst', [('t', '_LIT_56', '*', 'op'), ('t', 'STRING', 'STRING', None), ('t', '_LIT_57', '*', '('), ('n', 'args'), ('t', '_LIT_58', '*', ')')]),
    ('opfnst', [('t', 'POINTER', 'POINTER', None), ('t', '_LIT_59', '*', '='), ('n', 'opfn'), ('t', '_LIT_60', '*', '('), ('n', 'args'), ('t', '_LIT_61', '*', ')')]),
    ('opfn', [('t', '_LIT_62', '*', 'serialize')]),
    ('opfn', [('t', '_LIT_63', '*', 'deserialize')]),
    ('opfn', [('t', '_LIT_64', '*', 'encode')]),
    ('opfn', [('t', '_LIT_65', '*', 'decode')]),
    ('opfn', [('t', '_LIT_66', '*', 'hash')]),
    ('callstmt', [('n', 'call')]),
    ('expr', [('n', 'ternary')]),
    ('ternary', [('n', 'coalesce'), ('t', '_LIT_67', '*', '?'), ('n', 'expr'), ('t', '_LIT_68', '*', ':'), ('n', 'ternary')]),
    ('ternary', [('n', 'coalesce')]),
    ('coalesce', [('n', 'coalesce'), ('t', '_LIT_69', '*', '??'), ('n', 'orx')]),
    ('coalesce', [('n', 'orx')]),
    ('orx', [('n', 'orx'), ('t', '_LIT_70', '*', 'or'), ('n', 'andx')]),
    ('orx', [('n', 'andx')]),
    ('andx', [('n', 'andx'), ('t', '_LIT_71', '*', 'and'), ('n', 'notx')]),
    ('andx', [('n', 'notx')]),
    ('notx', [('t', '_LIT_72', '*', 'not'), ('n', 'notx')]),
    ('notx', [('n', 'cmp')]),
    ('cmp', [('n', 'cmp'), ('n', 'cmpop'), ('n', 'addx')]),
    ('cmp', [('n', 'addx')]),
    ('cmpop', [('t', '_LIT_73', '*', '==')]),
    ('cmpop', [('t', '_LIT_74', '*', '!=')]),
    ('cmpop', [('t', '_LIT_75', '*', '<')]),
    ('cmpop', [('t', '_LIT_76', '*', '<=')]),
    ('cmpop', [('t', '_LIT_77', '*', '>')]),
    ('cmpop', [('t', '_LIT_78', '*', '>=')]),
    ('cmpop', [('t', '_LIT_79', '*', 'in')]),
    ('addx', [('n', 'addx'), ('t', '_LIT_80', '*', '+'), ('n', 'mulx')]),
    ('addx', [('n', 'addx'), ('t', '_LIT_81', '*', '-'), ('n', 'mulx')]),
    ('addx', [('n', 'mulx')]),
    ('mulx', [('n', 'mulx'), ('t', '_LIT_82', '*', '*'), ('n', 'powx')]),
    ('mulx', [('n', 'mulx'), ('t', '_LIT_83', '*', '/'), ('n', 'powx')]),
    ('mulx', [('n', 'mulx'), ('t', '_LIT_84', '*', '%'), ('n', 'powx')]),
    ('mulx', [('n', 'powx')]),
    ('powx', [('n', 'unary'), ('t', '_LIT_85', '*', '**'), ('n', 'powx')]),
    ('powx', [('n', 'unary')]),
    ('unary', [('t', '_LIT_86', '*', '-'), ('n', 'unary')]),
    ('unary', [('t', '_LIT_87', '*', 'exists'), ('t', 'POINTER', 'POINTER', None)]),
    ('unary', [('n', 'atom')]),
    ('atom', [('t', 'INT', 'INT', None)]),
    ('atom', [('t', 'FLOAT', 'FLOAT', None)]),
    ('atom', [('t', 'STRING', 'STRING', None)]),
    ('atom', [('t', '_LIT_88', '*', 'true')]),
    ('atom', [('t', '_LIT_89', '*', 'false')]),
    ('atom', [('t', '_LIT_90', '*', 'null')]),
    ('atom', [('t', 'POINTER', 'POINTER', None)]),
    ('atom', [('n', 'read')]),
    ('atom', [('n', 'call')]),
    ('atom', [('n', 'listx')]),
    ('atom', [('n', 'dictx')]),
    ('atom', [('n', 'evalx')]),
    ('atom', [('t', '_LIT_91', '*', '('), ('n', 'expr'), ('t', '_LIT_92', '*', ')')]),
    ('read', [('t', '_LIT_93', '*', '$('), ('t', 'POINTER', 'POINTER', None), ('t', '_LIT_94', '*', ')')]),
    ('read', [('t', '_LIT_95', '*', '$('), ('t', 'POINTER', 'POINTER', None), ('t', '_LIT_96', '*', ')'), ('t', '_LIT_97', '*', 'raw')]),
    ('read', [('t', '_LIT_98', '*', '$('), ('t', 'POINTER', 'POINTER', None), ('t', '_LIT_99', '*', '??'), ('n', 'expr'), ('t', '_LIT_100', '*', ')')]),
    ('call', [('t', 'IDENT', 'IDENT', None), ('t', '_LIT_101', '*', '('), ('n', 'args'), ('t', '_LIT_102', '*', ')')]),
    ('call', [('t', '_LIT_103', '*', 'raw'), ('t', '_LIT_104', '*', '('), ('n', 'expr'), ('t', '_LIT_105', '*', ')')]),
    ('args', []),
    ('args', [('n', 'arg_list')]),
    ('arg_list', [('n', 'arg')]),
    ('arg_list', [('n', 'arg_list'), ('t', '_LIT_106', '*', ','), ('n', 'arg')]),
    ('arg', [('n', 'expr')]),
    ('arg', [('t', 'IDENT', 'IDENT', None), ('t', '_LIT_107', '*', ':'), ('n', 'expr')]),
    ('listx', [('t', '_LIT_108', '*', '['), ('n', 'elems'), ('t', '_LIT_109', '*', ']')]),
    ('elems', []),
    ('elems', [('n', 'expr_list')]),
    ('expr_list', [('n', 'expr')]),
    ('expr_list', [('n', 'expr_list'), ('t', '_LIT_110', '*', ','), ('n', 'expr')]),
    ('dictx', [('t', '_LIT_111', '*', '{'), ('n', 'pairs'), ('t', '_LIT_112', '*', '}')]),
    ('pairs', []),
    ('pairs', [('n', 'pair_list')]),
    ('pair_list', [('n', 'pair')]),
    ('pair_list', [('n', 'pair_list'), ('t', '_LIT_113', '*', ','), ('n', 'pair')]),
    ('pair', [('t', 'STRING', 'STRING', None), ('t', '_LIT_114', '*', ':'), ('n', 'expr')]),
    ('pair', [('t', 'IDENT', 'IDENT', None), ('t', '_LIT_115', '*', ':'), ('n', 'expr')]),
    ('evalx', [('t', '_LIT_116', '*', 'eval'), ('t', '_LIT_117', '*', '{'), ('n', 'block'), ('t', '_LIT_118', '*', '}')]),
    ('evalx', [('t', '_LIT_119', '*', 'eval'), ('t', '_LIT_120', '*', '{'), ('n', 'block'), ('t', '_LIT_121', '*', '}'), ('t', '_LIT_122', '*', 'select'), ('t', 'POINTER', 'POINTER', None)]),
]

_NT_INDEX = {'program': [0], 'block': [1, 2], 'stmts': [3, 4], 'seps_opt': [5, 6], 'seps': [7, 8], 'sep': [9, 10], 'stmt': [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], 'suite': [30, 31, 32], 'assign': [33, 34], 'copy': [35, 36, 37], 'del': [38, 39], 'ptr_list': [40, 41], 'assertst': [42, 43], 'ifst': [44], 'elifs': [45, 46, 47], 'else_opt': [48, 49, 50], 'foreachst': [51, 52], 'whilest': [53], 'dowhilest': [54], 'tryst': [55], 'except_opt': [56, 57], 'finally_opt': [58, 59], 'defst': [60], 'params': [61, 62], 'param_list': [63, 64], 'defopts': [65, 66], 'failopt': [67, 68], 'returnst': [69, 70], 'raisest': [71], 'breakst': [72], 'continuest': [73], 'exitst': [74], 'execst': [75, 76, 77], 'opst': [78, 79], 'opfnst': [80], 'opfn': [81, 82, 83, 84, 85], 'callstmt': [86], 'expr': [87], 'ternary': [88, 89], 'coalesce': [90, 91], 'orx': [92, 93], 'andx': [94, 95], 'notx': [96, 97], 'cmp': [98, 99], 'cmpop': [100, 101, 102, 103, 104, 105, 106], 'addx': [107, 108, 109], 'mulx': [110, 111, 112, 113], 'powx': [114, 115], 'unary': [116, 117, 118], 'atom': [119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131], 'read': [132, 133, 134], 'call': [135, 136], 'args': [137, 138], 'arg_list': [139, 140], 'arg': [141, 142], 'listx': [143], 'elems': [144, 145], 'expr_list': [146, 147], 'dictx': [148], 'pairs': [149, 150], 'pair_list': [151, 152], 'pair': [153, 154], 'evalx': [155, 156]}
_START = 'program'

def _matches(sym, token_type, token_value):
    _, name, tok_t, tok_v = sym
    if tok_t != '*' and token_type != tok_t:
        return False
    if tok_v is not None and token_value != tok_v:
        return False
    return True


def _parse_earley(tokens):
    n = len(tokens)
    chart = [[] for _ in range(n + 1)]
    in_chart = [set() for _ in range(n + 1)]

    def add(i, item):
        if item not in in_chart[i]:
            chart[i].append(item)
            in_chart[i].add(item)

    for ri in _NT_INDEX.get(_START, []):
        add(0, (ri, 0, 0))

    for i in range(n + 1):
        j = 0
        while j < len(chart[i]):
            rule_idx, dot, origin = chart[i][j]
            j += 1
            head, body = _RULES[rule_idx]
            if dot == len(body):
                for p_ri, p_dot, p_orig in chart[origin]:
                    _, p_body = _RULES[p_ri]
                    if p_dot < len(p_body) and p_body[p_dot][0] == 'n' and p_body[p_dot][1] == head:
                        add(i, (p_ri, p_dot + 1, p_orig))
            elif body[dot][0] == 'n':
                for ri in _NT_INDEX.get(body[dot][1], []):
                    add(i, (ri, 0, i))
            else:
                if i < n and _matches(body[dot], tokens[i].type, tokens[i].value):
                    add(i + 1, (rule_idx, dot + 1, origin))

    completed = {}
    for e, items in enumerate(chart):
        for rule_idx, dot, origin in items:
            head, body = _RULES[rule_idx]
            if dot == len(body):
                key = (head, origin, e)
                if key in completed:
                    completed[key].append(rule_idx)
                else:
                    completed[key] = [rule_idx]

    _memo = {}

    def _recover(ri, s, e):
        _result = None
        stack = [('R', ri, s, e)]

        while stack:
            tag = stack[-1][0]

            if tag == 'R':
                _, ri_, s_, e_ = stack.pop()
                key = ('r', ri_, s_, e_)
                if key in _memo:
                    _result = _memo[key]
                else:
                    head_, body_ = _RULES[ri_]
                    stack.append(('R_DONE', key, head_))
                    stack.append(('B', body_, 0, s_, e_))

            elif tag == 'R_DONE':
                _, key, head_ = stack.pop()
                _result = NonTerminalNode(head_, _result) if _result is not None else None
                _memo[key] = _result

            elif tag == 'B':
                _, body_, pos_, s_, e_ = stack.pop()
                bkey = (id(body_), pos_, s_, e_)
                if bkey in _memo:
                    _result = _memo[bkey]
                elif pos_ >= len(body_):
                    _result = [] if s_ == e_ else None
                    _memo[bkey] = _result
                else:
                    sym_ = body_[pos_]
                    if sym_[0] == 't':
                        if s_ >= e_ or not _matches(sym_, tokens[s_].type, tokens[s_].value):
                            _result = None
                            _memo[bkey] = None
                        else:
                            _p = tokens[s_].position
                            _tpos = Position(_p.line, _p.col, _p.offset) if _p is not None else None
                            tnode = TerminalNode(sym_[1], tokens[s_].type, tokens[s_].value, _tpos)
                            stack.append(('B_TERM_DONE', bkey, tnode))
                            stack.append(('B', body_, pos_ + 1, s_ + 1, e_))
                    else:
                        stack.append(('B_NT_LOOP', bkey, body_, pos_, s_, e_, sym_[1], s_))

            elif tag == 'B_TERM_DONE':
                _, bkey, tnode = stack.pop()
                if _result is None:
                    _memo[bkey] = None
                else:
                    _result = [tnode] + _result
                    _memo[bkey] = _result

            elif tag == 'B_NT_LOOP':
                _, bkey, body_, pos_, s_, e_, name_, mid_ = stack.pop()
                if mid_ > e_:
                    _result = None
                    _memo[bkey] = None
                else:
                    stack.append(('B_NT_AFTER_FIND', bkey, body_, pos_, s_, e_, name_, mid_))
                    stack.append(('F', name_, s_, mid_))

            elif tag == 'B_NT_AFTER_FIND':
                _, bkey, body_, pos_, s_, e_, name_, mid_ = stack.pop()
                node_ = _result
                if node_ is None:
                    stack.append(('B_NT_LOOP', bkey, body_, pos_, s_, e_, name_, mid_ + 1))
                else:
                    stack.append(('B_NT_AFTER_TAIL', bkey, body_, pos_, s_, e_, name_, mid_, node_))
                    stack.append(('B', body_, pos_ + 1, mid_, e_))

            elif tag == 'B_NT_AFTER_TAIL':
                _, bkey, body_, pos_, s_, e_, name_, mid_, node_ = stack.pop()
                tail_ = _result
                if tail_ is None:
                    stack.append(('B_NT_LOOP', bkey, body_, pos_, s_, e_, name_, mid_ + 1))
                else:
                    _result = [node_] + tail_
                    _memo[bkey] = _result

            elif tag == 'F':
                _, name_, s_, e_ = stack.pop()
                fkey = ('f', name_, s_, e_)
                if fkey in _memo:
                    _result = _memo[fkey]
                else:
                    items_ = completed.get((name_, s_, e_), [])
                    if not items_:
                        _result = None
                        _memo[fkey] = None
                    else:
                        stack.append(('F_NEXT', fkey, s_, e_, items_, 0))
                        stack.append(('R', items_[0], s_, e_))

            elif tag == 'F_NEXT':
                _, fkey, s_, e_, items_, idx_ = stack.pop()
                node_ = _result
                if node_ is not None:
                    _result = node_
                    _memo[fkey] = node_
                elif idx_ + 1 < len(items_):
                    stack.append(('F_NEXT', fkey, s_, e_, items_, idx_ + 1))
                    stack.append(('R', items_[idx_ + 1], s_, e_))
                else:
                    _result = None
                    _memo[fkey] = None

        return _result

    for rule_idx, dot, origin in chart[n]:
        head, body = _RULES[rule_idx]
        if head == _START and dot == len(body) and origin == 0:
            node = _recover(rule_idx, 0, n)
            if node is not None:
                return node
    raise ValueError('Parse failed')


def parse(tokens):
    return _parse_earley(list(tokens))

